services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: auth-api
    ports:
      - "5001:8080"
    networks:
      - app-net

  core-api:
    build:
      context: .
      dockerfile: Dockerfile.core
    container_name: core-api
    ports:
      - "5002:8080"
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    driver: bridge