FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["TheBand.AuthApi/TheBand.AuthApi.csproj", "TheBand.AuthApi/"]
RUN dotnet restore "TheBand.AuthApi/TheBand.AuthApi.csproj"
COPY . .
WORKDIR "/src/TheBand.AuthApi"
RUN dotnet publish "TheBand.AuthApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_HTTP_PORTS=8080
ENTRYPOINT ["dotnet", "TheBand.AuthApi.dll"]