FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["TheBand.CoreApi/TheBand.CoreApi.csproj", "TheBand.CoreApi/"]
RUN dotnet restore "TheBand.CoreApi/TheBand.CoreApi.csproj"
COPY . .
WORKDIR "/src/TheBand.CoreApi"
RUN dotnet publish "TheBand.CoreApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_HTTP_PORTS=8080
ENTRYPOINT ["dotnet", "TheBand.CoreApi.dll"]